

"""add tool_invocations table

Revision ID: 2fc8a9cc401c
Revises: 645b4437f7fc
Create Date: 2026-02-03 22:20:59.544251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2fc8a9cc401c'
down_revision = '645b4437f7fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_invocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_invocations_tool_name'), 'tool_invocations', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_invocations_user_id'), 'tool_invocations', ['user_id'], unique=False)
    # Note: The following indexes were detected as missing but existing in DB - skipping for now
    # op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    # op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_tool_invocations_user_id'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_tool_name'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    # ### end Alembic commands ###
